version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: postgres_agenda
    environment:
      POSTGRES_USER: agenda
      POSTGRES_PASSWORD: agenda
      POSTGRES_DB: agenda
    volumes:
      - ./data:/var/lib/postgresql/data
  agenda_app:
    depends_on:
      - db
    image: sebashub/agenda_app:latest
    container_name: agenda_app
