version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: postgres_agenda
    environment:
      POSTGRES_USER: agenda
      POSTGRES_PASSWORD: agenda
      POSTGRES_DB: agenda
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
