# Generated by Django 4.2.7 on 2023-11-08 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_do_evento', models.CharField(max_length=500)),
                ('data_e_hora', models.DateTimeField()),
                ('descricao', models.CharField(max_length=50)),
            ],
        ),
    ]
